# Deployment Definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: app
          image: icano/udacity-capstone:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: MONGODB_URI
              value: mongodb://mongo:27017/todos
          imagePullPolicy: Always

---
# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: todos
spec:
  selector:
    app: todos
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer