version: "3.7"

services:
  database:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: icano/udacity-capstone:latest
    depends_on:
      - database
    environment:
      PORT: 80
      MONGODB_URI: mongodb://database:27017/todos
    ports:
      - 8000:80