---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Control Plane'

Parameters:
  ClusterName:
    Description: Name of the cluster, used with the nodes
    Type: String

  NetworkStackName:
    Description: The name of the network stack to grab vpc and subnets.
    Type: String

  NodeGroupMinSize:
    Description: Minimum size of Node Group ASG.
    Type: Number
    Default: 1

  NodeGroupMaxSize:
    Description: Maximum size of Node Group ASG. Set to at least 1 greater than NodeAutoScalingGroupDesiredCapacity.
    Type: Number
    Default: 4

  NodeGroupDesiredSize:
    Description: Desired capacity of Node Group ASG.
    Type: Number
    Default: 3

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ControlPlaneSecurityGroup
        SubnetIds: !Split
          - ","
          - Fn::ImportValue:
              !Sub "${NetworkStackName}-SUBIDS"
      RoleArn: !GetAtt EksServiceRole.Arn
      Version: 1.14

  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStackName}-VPCID"

  EksServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
      RoleName: !Sub "EksSvcRole-${AWS::StackName}"

  EKSNodegroup:
    DependsOn: EKSCluster
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      InstanceTypes:
        - t3.small
      NodeRole: !GetAtt NodeInstanceRole.Arn
      ScalingConfig:
        MinSize: !Ref NodeGroupMinSize
        DesiredSize: !Ref NodeGroupDesiredSize
        MaxSize: !Ref NodeGroupMaxSize
      Subnets: !Split
        - ","
        - Fn::ImportValue:
            !Sub "${NetworkStackName}-SUBIDS"

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      RoleName: !Sub "EksNodeGroupRole-${AWS::StackName}"

Outputs:
  EKSId:
    Description: The EKS Id
    Value: !Ref EKSCluster
    Export:
      Name: !Sub "${AWS::StackName}-EKSID"
  SecurityGroups:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Ref ControlPlaneSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-EKSCPSG"